services:
  - type: web
    name: vet-review-analysis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: false
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false